name: Builds Artifact and Release

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: EFI

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      JOB_TYPE: BUILD

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Zip EFI
      run: |
        rm -Rf screenshot
        rm -Rf .gitignore
        rm -Rf "XPS 9700 MacbookAir 9.1.ioreg"
        rm -Rf README.md
        rm -Rf ".github"
        rm -Rf ".git"
        
        zip -r DellXPS9700RAlderLake.zip .
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: DellXPS9700RAlderLake
        path: DellXPS9700RAlderLake.zip
        
    - name: Upload build
      uses: svenstaro/upload-release-action@2.9.0
      if: github.event_name != 'pull_request'
      with:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         file: ./*.zip
         tag: ${{ github.ref }}
         release_name: EFI DellXPS9700 Hackintosh
         body: ${{ github.event_name != 'release' && github.event.head_commit.message || '' }}
         file_glob: true
         overwrite: true
